Fix NoMethod error `stacks` in WebHooksController
Summary
-------

When receiving messages for repositories we've not yet present in the
shipit datastore, `Repositorty.from_github_repo_name` will be nil -
resulting in a NoMethod error:

```
NoMethodError undefined method `stacks' for nil:NilClass
```

This introduces a _Null Object_ to represent repos shipit doesn't yet
know about, but for which it will receive messages.